---
# tasks file for docker
- name: creating a docker repository
  yum_repository:
       description: repo for docker
       name: docker-ce
       baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
       gpgcheck: no

- name: Install docker
  yum:
    name: docker-ce
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
